### ISSUE TITLE
Como usuario puedo ver la sección SBT traducida

### ISSUE THREAD

**Issue by poguez** [scalamx/scala_school#9]
Para e-evolution

**Comment by poguez** [comment]
traduccion plz :point_up_2:

**Comment by omendezmorales** [comment]
Te refieres a esta seccion, 
www.scala-sbt.org/release/tutorial/ 
o tienes en mente alguna otra?

**Comment by lankor** [comment]
Esa ya la estoy traduciendo

**Comment by poguez** [comment]
tienen avances @lankor @omendezmorales ? podríamos revisarlos para evitar retrabajo.

**Comment by lankor** [comment]
En mi repo está, cree la rama SBT. Ahí está un avance ya

Enviado desde mi iPhone

**Comment by omendezmorales** [comment]
podria contribuir, pero desconozco el avance de lankor y en que parte en específico puedo ayudar,.

Lankor?

Saludos, 

Orlando.Noé Domínguez Porras notifications@github.com wrote:tienen avances @lankor @omendezmorales ? podríamos revisarlos para evitar retrabajo.

**Comment by poguez** [comment]
@omendezmorales revisa los últimos 2 commits 
https://github.com/lankor/scala_school/commits/sbt

**Comment by poguez** [comment]
@zoek1 revisa #32 please :P

**Comment by omendezmorales** [comment]
ok, voy a trabjar en ello. No te pude contestar antesporque estaba_  de vacaciones_ :-
